ARM_STIFFNESS = 1e3
ARM_DAMPING = 100
ARM_FORCE_LIMIT = 50

HAND_STIFFNESS = 1e3
HAND_DAMPING = 100
HAND_FORCE_LIMIT = 50


ARM_POSE_PD_EE_POS_LOWER = -0.01
ARM_POSE_PD_EE_POS_UPPER = 0.01
ARM_POSE_PD_EE_ROT_LOWER = -0.05
ARM_POSE_PD_EE_ROT_UPPER = 0.05

ARM_DOF = 7
HAND_DOF = 10

CONTACT_THRESHOLD = 0.1

NORMALIZE_PDEE = True
NORMALIZE_PD_HANDJOINT = True
