collision_spheres:
  link_base:
    - "center": [ 0.0, 0.0, 0.1 ]
      "radius": 0.052
    - "center": [ -0.0, 0.0, 0.049 ]
      "radius": 0.052
  link1:
    - "center": [ 0.0, -0.004, -0.001 ]
      "radius": 0.053
    - "center": [ -0.002, -0.011, -0.074 ]
      "radius": 0.041
    - "center": [ 0.001, 0.025, 0.001 ]
      "radius": 0.051
    - "center": [ 0.018, 0.001, -0.083 ]
      "radius": 0.033
  link2:
    - "center": [ -0.001, -0.107, 0.011 ]
      "radius": 0.05
    - "center": [ 0.005, -0.11, 0.075 ]
      "radius": 0.05
    - "center": [ 0.0, -0.147, -0.0 ]
      "radius": 0.052
    - "center": [ 0.002, -0.008, 0.097 ]
      "radius": 0.032
    - "center": [ -0.005, -0.046, 0.097 ]
      "radius": 0.031
    - "center": [ -0.002, 0.023, 0.096 ]
      "radius": 0.03
  link3:
    - "center": [ 0.04, 0.035, 0.001 ]
      "radius": 0.046
    - "center": [ 0.051, -0.027, 0.002 ]
      "radius": 0.045
    - "center": [ -0.006, 0.015, -0.061 ]
      "radius": 0.04
    - "center": [ 0.013, 0.036, -0.019 ]
      "radius": 0.032
  link4:
    - "center": [ 0.077, -0.12, -0.0 ]
      "radius": 0.047
    - "center": [ 0.078, -0.086, -0.001 ]
      "radius": 0.046
    - "center": [ 0.016, -0.017, 0.087 ]
      "radius": 0.024
    - "center": [ 0.002, 0.017, 0.086 ]
      "radius": 0.024
    - "center": [ 0.078, -0.083, 0.071 ]
      "radius": 0.046
  link5:
    - "center": [ 0.0, 0.046, 0.0 ]
      "radius": 0.045
    - "center": [ 0.005, 0.014, -0.145 ]
      "radius": 0.038
    - "center": [ -0.013, -0.012, -0.149 ]
      "radius": 0.033
    - "center": [ 0.016, -0.011, -0.149 ]
      "radius": 0.033
    - "center": [ -0.005, 0.05, -0.1 ]
      "radius": 0.026
    - "center": [ -0.018, 0.004, -0.145 ]
      "radius": 0.034
    - "center": [ 0.001, 0.065, -0.06 ]
      "radius": 0.024
  link6:
    - "center": [ 0.05, 0.012, -0.0 ]
      "radius": 0.042
    - "center": [ -0.003, -0.003, 0.026 ]
      "radius": 0.035
    - "center": [ 0.075, 0.05, 0.002 ]
      "radius": 0.041
  thumb_base:
    - "center": [ -0.029, -0.005, 0.013 ]
      "radius": 0.025
    - "center": [ -0.046, -0.013, -0.035 ]
      "radius": 0.021
    - "center": [ -0.005, -0.005, -0.007 ]
      "radius": 0.02
    - "center": [ -0.046, -0.011, -0.007 ]
      "radius": 0.019
    - "center": [ -0.012, -0.015, -0.045 ]
      "radius": 0.019
    - "center": [ -0.001, -0.011, -0.04 ]
      "radius": 0.018
#  thumb_L1:
#    - "center": [ 0.013, -0.001, 0.001 ]
#      "radius": 0.011
#    - "center": [ 0.02, -0.003, 0.008 ]
#      "radius": 0.01
#  thumb_L2:
#    - "center": [ 0.042, 0.01, 0.004 ]
#      "radius": 0.015
#    - "center": [ 0.015, -0.001, 0.004 ]
#      "radius": 0.014
#    - "center": [ 0.028, 0.006, 0.004 ]
#      "radius": 0.015
#    - "center": [ 0.047, 0.015, 0.004 ]
#      "radius": 0.015
#    - "center": [ 0.003, -0.007, 0.004 ]
#      "radius": 0.012
#  index_L1:
#    - "center": [ 0.007, -0.001, -0.001 ]
#      "radius": 0.013
#    - "center": [ 0.024, -0.0, -0.001 ]
#      "radius": 0.013
#  index_L2:
#    - "center": [ 0.008, -0.007, -0.0 ]
#      "radius": 0.012
#    - "center": [ 0.023, -0.014, -0.0 ]
#      "radius": 0.011
#    - "center": [ 0.013, -0.01, -0.0 ]
#      "radius": 0.012
#    - "center": [ 0.031, -0.016, -0.001 ]
#      "radius": 0.01
#  middle_L1:
#    - "center": [ 0.007, -0.001, -0.001 ]
#      "radius": 0.013
#    - "center": [ 0.024, -0.0, -0.001 ]
#      "radius": 0.013
#  middle_L2:
#    - "center": [ 0.008, -0.007, -0.0 ]
#      "radius": 0.012
#    - "center": [ 0.023, -0.014, -0.0 ]
#      "radius": 0.011
#    - "center": [ 0.013, -0.01, -0.0 ]
#      "radius": 0.012
#    - "center": [ 0.031, -0.016, -0.001 ]
#      "radius": 0.01
#  ring_L1:
#    - "center": [ 0.007, -0.001, -0.001 ]
#      "radius": 0.013
#    - "center": [ 0.024, -0.0, -0.001 ]
#      "radius": 0.013
#  ring_L2:
#    - "center": [ 0.008, -0.007, -0.0 ]
#      "radius": 0.012
#    - "center": [ 0.023, -0.014, -0.0 ]
#      "radius": 0.011
#    - "center": [ 0.013, -0.01, -0.0 ]
#      "radius": 0.012
#    - "center": [ 0.031, -0.016, -0.001 ]
#      "radius": 0.01
#  pinky_L1:
#    - "center": [ 0.007, -0.001, -0.001 ]
#      "radius": 0.013
#    - "center": [ 0.024, -0.0, -0.001 ]
#      "radius": 0.013
#  pinky_L2:
#    - "center": [ 0.008, -0.007, -0.0 ]
#      "radius": 0.012
#    - "center": [ 0.023, -0.014, -0.0 ]
#      "radius": 0.011
#    - "center": [ 0.013, -0.01, -0.0 ]
#      "radius": 0.012
#    - "center": [ 0.031, -0.016, -0.001 ]
#      "radius": 0.01